[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = "neovim/nvim-lsp"

[[plugins]]
repo = "neovim/nvim-lspconfig"

[[plugins]]
repo = "alexaandru/nvim-lspupdate"

[[plugins]]
repo = "liuchengxu/vista.vim"
hook_add = '''
    let g:vista_sidebar_width = 30
    let g:vista_echo_cursor = 0
    let g:vista_default_executive = 'nvim_lsp'
    nnoremap <silent><Leader>v :Vista!!<CR>
'''

[[plugins]]
repo = "Shougo/deoplete.nvim"
lazy = 1
on_i = 1
depends = ['deoplete-lsp']
hook_source = '''
    let g:deoplete#enable_at_startup = 1
    call deoplete#custom#option({
        \ 'auto_complete': v:true,
        \ 'min_pattern_length': 2,
        \ 'auto_complete_delay': 0,
        \ 'auto_refresh_delay': 20,
        \ 'refresh_always': v:true,
        \ 'smart_case': v:true,
        \ 'camel_case': v:true,
        \ 'ignore_case': v:false,
        \ })
'''

[[plugins]]
repo = "deoplete-plugins/deoplete-lsp"
lazy = 1
on_i = 1
hook_add = '''
let g:deoplete#lsp#handler_enabled = v:false
'''

[[plugins]]
repo = "Shougo/deoppet.nvim"
hook_add = '''
command! DeoppetEdit exe 'e ~/.vim/bundle/vim-snippets/snippets/' . &filetype . '.snip'
call deoppet#initialize()
call deoppet#custom#option('snippets',
\ map(globpath(&runtimepath, '*snippets', 1, 1),
\     { _, val -> { 'path': val } }))


imap <C-k>  <Plug>(deoppet_expand)
imap <C-f>  <Plug>(deoppet_jump_forward)
imap <C-b>  <Plug>(deoppet_jump_backward)
xmap <C-l>  <Plug>(deoppet_select_text)
xmap <C-x>  <Plug>(deoppet_cut_text)
'''

[[plugins]]
repo = "Shougo/neosnippet-snippets"

[[plugins]]
repo = "Shougo/denite.nvim"
hook_add = '''
nnoremap <silent><Leader>f :Denite file/rec<CR>
nnoremap <silent><Leader>b :Denite buffer<CR>
nnoremap <silent><Leader>: :Denite command_history<CR>
nnoremap <silent><Leader>p :Denite register<CR>
nnoremap <silent><Leader>s :Denite source<CR>
nnoremap <silent><Leader>c :Denite colorscheme<CR>
nnoremap <silent><Leader>h :Denite help<CR>


autocmd FileType denite call s:denite_my_settings()
function! s:denite_my_settings() abort
  nnoremap <silent><buffer><expr> l
  \ denite#do_map('do_action')
  nnoremap <silent><buffer><expr> d
  \ denite#do_map('do_action', 'delete')
  nnoremap <silent><buffer><expr> p
  \ denite#do_map('do_action', 'preview')
  nnoremap <silent><buffer><expr> q
  \ denite#do_map('quit')
  nnoremap <silent><buffer><expr> i
  \ denite#do_map('open_filter_buffer')
  nnoremap <silent><buffer><expr> h
  \ denite#do_map('toggle_select')
endfunction
'''

[[plugins]]
repo = "Shougo/deol.nvim"
hook_add = '''
nnoremap <silent><Leader>s :Deol<CR>
'''

[[plugins]]
repo = "thinca/vim-quickrun"
hook_add = '''
nnoremap <expr><silent> <C-c> quickrun#is_running() ? quickrun#sweep_sessions() : "\<C-c>"
let g:quickrun_config = get(g:, 'quickrun_config', {})

let g:quickrun_config._ = {
\   'runner'    : 'vimproc',
\   'runner/vimproc/updatetime' : 60,
\   'outputter' : 'error',
\   'outputter/error/success' : 'buffer',
\   'outputter/error/error'   : 'quickfix',
\   'outputter/buffer/split'  : '5',
\   'outputter/buffer/close_on_empty' : 1,
\ }

let g:quickrun_config.tex = {
\   'command' : 'ptex2pdf.exe',
\   'cmdopt' : '-l -ot -kanji=utf8'
\ }
'''

# operator
[[plugins]]
repo = "simeji/winresizer"


# view
[[plugins]]
repo = "flazz/vim-colorschemes"

[[plugins]]
repo = "upnt/vim-hold-colorscheme"

[[plugins]]
repo = "itchyny/lightline.vim"
hook_add = '''
    set laststatus=2
    set noshowmode
    
    let g:lightline = {
        \  'enable': { 'tabline': 1 },
    	\  'active': {
    	\         'left': [ [ 'mode', 'paste' ],
    	\                   [ 'readonly', 'myfilename', 'modified' ] ],
    	\         'right': [ [ 'percent' ],
    	\                    [ 'filetype'],
    	\                    [ 'fileformat', 'fileencoding' ] ]
        \   },
        \   'component_function': {
        \       'myfilename': 'LightlineFilename',
        \   },
    	\   'inactive': {
    	\         'left': [ [ 'filename' ] ],
    	\         'right': [ [ 'lineinfo' ],
    	\                    [ 'percent' ] ]
        \   },
    	\   'tabline': {
    	\         'left': [ [ 'tabs' ] ],
    	\         'right': [ [ 'close' ] ] 
        \   },
        \  'separator': { 'left': "\ue0b0 ", 'right': "\ue0b2 " },
        \  'subseparator': { 'left': "\ue0b1 ", 'right': "\ue0b3 " }
        \ } 
    function! LightlineFilename()
        let l:p = expand('%:t')
        if '' !=# l:p
            return l:p
        endif
        return '[No Name]'
    endfunction
'''


[[plugins]]
repo = 'skanehira/translate.vim'
hook_add = '''
let g:translate_source = "en"
let g:translate_target = "ja"
let g:translate_winsize = 10
let g:translate_popup_window = 1
nnoremap <Leader>t :Translate<CR>
vnoremap <Leader>t :'<,'>Translate<CR>
'''

[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = '''
nmap <Leader>w <Plug>(openbrowser-smart-search)
vmap <Leader>w <Plug>(openbrowser-smart-search)
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
nnoremap <silent><Leader>gd :Gvdiffsplit<CR>
nnoremap <silent><Leader>gb :Gblame<CR>
nnoremap <silent><Leader>gs :Git<CR>
nnoremap <silent><Leader>gp :Git push<CR>
'''

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
lazy = 1
on_cmd = ['help']
