[[plugins]]
repo = "neovim/nvim-lsp"

[[plugins]]
repo = "neovim/nvim-lspconfig"

[[plugins]]
repo = "anott03/nvim-lspinstall"

[[plugins]]
repo = "liuchengxu/vista.vim"
hook_add = '''
    let g:vista_sidebar_width = 30
    let g:vista_echo_cursor = 0
    let g:vista_default_executive = 'nvim_lsp'
    nnoremap <silent><Leader>v :Vista!!<CR>
'''

# complete
[[plugins]]
repo = "Shougo/deoplete.nvim"
lazy = 1
on_i = 1
depends = ['deoplete-lsp']
hook_source = '''
    let g:deoplete#enable_at_startup = 1
    call deoplete#custom#option({
        \ 'auto_complete': v:true,
        \ 'min_pattern_length': 2,
        \ 'auto_complete_delay': 0,
        \ 'auto_refresh_delay': 20,
        \ 'refresh_always': v:true,
        \ 'smart_case': v:true,
        \ 'camel_case': v:true,
        \ 'ignore_case': v:false,
        \ })
'''

[[plugins]]
repo = "deoplete-plugins/deoplete-lsp"
lazy = 1
on_i = 1
hook_add = '''
let g:deoplete#lsp#handler_enabled = v:false
'''

[[plugins]]
repo = "Shougo/denite.nvim"
hook_add = '''
nnoremap <silent><Leader>f :Denite file/rec<CR>
nnoremap <silent><Leader>: :Denite command_history<CR>
nnoremap <silent><Leader>p :Denite register<CR>
nnoremap <silent><Leader>s :Denite source<CR>
nnoremap <silent><Leader>c :Denite colorscheme<CR>
nnoremap <silent><Leader>h :Denite help<CR>


autocmd FileType denite call s:denite_my_settings()
function! s:denite_my_settings() abort
  nnoremap <silent><buffer><expr> l
  \ denite#do_map('do_action')
  nnoremap <silent><buffer><expr> d
  \ denite#do_map('do_action', 'delete')
  nnoremap <silent><buffer><expr> p
  \ denite#do_map('do_action', 'preview')
  nnoremap <silent><buffer><expr> q
  \ denite#do_map('quit')
  nnoremap <silent><buffer><expr> i
  \ denite#do_map('open_filter_buffer')
  nnoremap <silent><buffer><expr> h
  \ denite#do_map('toggle_select')
endfunction

'''

[[plugins]]
repo = "thinca/vim-quickrun"


# view
[[plugins]]
repo = "flazz/vim-colorschemes"

[[plugins]]
repo = "upnt/vim-hold-colorscheme"
hook_add = '''
let g:colorschemepath = stdpath('config')
'''

[[plugins]]
repo = "itchyny/lightline.vim"
hook_add = '''
    set laststatus=2
    set noshowmode
    
    let g:lightline = {
        \  'enable': { 'tabline': 1 },
    	\  'active': {
    	\         'left': [ [ 'mode', 'paste' ],
    	\                   [ 'readonly', 'myfilename', 'modified' ] ],
    	\         'right': [ [ 'percent' ],
    	\                    [ 'method', 'filetype'],
    	\                    [ 'fileformat', 'fileencoding' ] ]
        \   },
        \   'component_function': {
        \       'myfilename': 'LightlineFilename',
        \       'method': 'NearestMethodOrFunction',
        \   },
    	\   'inactive': {
    	\         'left': [ [ 'filename' ] ],
    	\         'right': [ [ 'lineinfo' ],
    	\                    [ 'percent' ] ]
        \   },
    	\   'tabline': {
    	\         'left': [ [ 'tabs' ] ],
    	\         'right': [ [ 'close' ] ] 
        \   },
        \  'colorscheme': 'solarized',
        \  'separator': { 'left': "\ue0b0 ", 'right': "\ue0b2 " },
        \  'subseparator': { 'left': "\ue0b1 ", 'right': "\ue0b3 " }
        \ } 
    function! LightlineFilename()
        let l:p = expand('%:t')
        if '' !=# l:p
            return l:p
        endif
        return '[No Name]'
    endfunction

    function! NearestMethodOrFunction() abort
        let l:func_name = get(b:, 'vista_nearest_method_or_function', '')
        if l:func_name != ''
            return 'ïž” ' . l:func_name
        endif
        return ''
    endfunction
   
    augroup LightLineOnVista
        autocmd!
        autocmd VimEnter * call vista#RunForNearestMethodOrFunction()
    augroup END   
'''
