[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'nvim-lua/popup.nvim'

[[plugins]]
repo = 'neoclide/coc.nvim'
merged = 0
hook_add = '''
inoremap <silent><expr> <TAB>
      \ pumvisible() ? coc#_select_confirm() :
      \ coc#expandableOrJumpable() ? "\<C-r>=coc#rpc#request('doKeymap', ['snippets-expand-jump',''])\<CR>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()

function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

let g:coc_snippet_next = '<C-j>'
let g:coc_snippet_prev = '<C-k>'
let g:coc_global_extensions = ['coc-git', 'coc-lists', 'coc-marketplace', 'coc-pairs', 'coc-snippets']
nnoremap <Leader>jf :call CocAction('jumpDefinition')<CR>
nnoremap <Leader>jd :call CocAction('jumpDeclaration')<CR>
nnoremap <Leader>ji :call CocAction('jumpImplementation')<CR>
nnoremap <Leader>jr :call CocAction('jumpReferences')<CR>
nnoremap <Leader>ch :call CocAction('doHover')<CR>
nnoremap <Leader>cr :call CocAction('rename')<CR>
nnoremap <Leader>ci :call CocAction('jumpImplementation')<CR>
nnoremap <Leader>cf :call CocAction('format')<CR>
nnoremap <silent><Leader>d :CocList files<CR>
nnoremap <silent><Leader>b :CocList buffers<CR>
nnoremap <silent><Leader>h :CocList helptags<CR>
nnoremap <silent><Leader>o :CocList outline<CR>
'''

[[plugins]]
repo = 'josa42/vim-lightline-coc'

[[plugins]]
repo = 'jalvesaq/Nvim-R'
rev = 'stable'
hook_add = '''
let g:R_path = "C:\\Users\\shun-\\scoop\\shims\\"
let g:R_auto_start = 1
vmap <C-l> <Plug>RDSendSelection
nmap <C-l> <Plug>RDSendLine
let g:r_syntax_folding = 1
'''

[[plugins]]
repo = 'lervag/vimtex'
hook_add = '''
let g:vimtex_view_general_viewer="SumatraPDF"
'''

[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = '''
nnoremap <silent><Leader>f :execute('Defx -buffer-name=' . tabpagenr())<CR>
function! Tabopen(context) abort
    execute('tabe ' . expand(a:context.targets[0]))
endfunction
function! s:defx_my_settings() abort
    " Define mappings
    nnoremap <silent><buffer><expr> l
	\ defx#is_directory() ?
	\ defx#do_action('open_tree', 'toggle') :
	\ defx#do_action('drop')
    nnoremap <silent><buffer><expr> t
	\ defx#do_action('call', 'Tabopen')
    nnoremap <silent><buffer><expr> c
    \ defx#do_action('copy')
    nnoremap <silent><buffer><expr> m
    \ defx#do_action('move')
    nnoremap <silent><buffer><expr> p
    \ defx#do_action('paste')
    nnoremap <silent><buffer><expr> o
    \ defx#do_action('open')
    nnoremap <silent><buffer><expr> P
    \ defx#do_action('preview')
    nnoremap <silent><buffer><expr> K
    \ defx#do_action('new_directory')
    nnoremap <silent><buffer><expr> N
    \ defx#do_action('new_file')
    nnoremap <silent><buffer><expr> M
    \ defx#do_action('new_multiple_files')
    nnoremap <silent><buffer><expr> C
    \ defx#do_action('toggle_columns',
    \                'mark:indent:icon:filename:type:size:time')
    nnoremap <silent><buffer><expr> S
    \ defx#do_action('toggle_sort', 'time')
    nnoremap <silent><buffer><expr> d
    \ defx#do_action('remove')
    nnoremap <silent><buffer><expr> r
    \ defx#do_action('rename')
    nnoremap <silent><buffer><expr> !
    \ defx#do_action('execute_command')
    nnoremap <silent><buffer><expr> x
    \ defx#do_action('execute_system')
    nnoremap <silent><buffer><expr> yy
    \ defx#do_action('yank_path')
    nnoremap <silent><buffer><expr> .
    \ defx#do_action('toggle_ignored_files')
    nnoremap <silent><buffer><expr> ;
    \ defx#do_action('repeat')
    nnoremap <silent><buffer><expr> h
    \ defx#do_action('cd', ['..'])
    nnoremap <silent><buffer><expr> ~
    \ defx#do_action('cd')
    nnoremap <silent><buffer><expr> q
    \ defx#do_action('quit')
    nnoremap <silent><buffer><expr> <Space>
    \ defx#do_action('toggle_select')
    nnoremap <silent><buffer><expr> *
    \ defx#do_action('toggle_select_all')
    nnoremap <silent><buffer><expr> <C-l>
    \ defx#do_action('redraw')
    nnoremap <silent><buffer><expr> <C-g>
    \ defx#do_action('print')
    nnoremap <silent><buffer><expr> cd
    \ defx#do_action('change_vim_cwd')
endfunction
call defx#custom#option('_', {
    \ 'split': 'vertical',
    \ 'floating_preview': v:true,
    \ 'preview_height': 30,
    \ 'preview_width': 100,
    \ 'winwidth': 25,
    \ 'toggle': v:true,
    \ 'focus': v:false,
    \ 'columns': 'indent:git:icons:filename:type',
    \ 'ignored_files': '.*,*.aux,*.log,*.synctex.gz,*.dvi,*.fdb_latexmk,*.fls'
    \ })
call defx#custom#column('git', {
    \ 'show_ignored': 0,
    \ 'column_length': 2
    \ })
augroup MyDefx
    au!
    au filetype defx setl nonumber
    au filetype defx setl norelativenumber
    au filetype defx call s:defx_my_settings()
augroup END
'''

[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
repo = 'kristijanhusak/defx-git'

[[plugins]]
repo = 'Shougo/deol.nvim'
hook_add = '''
augroup MyDeol
    au!
    au VimEnter *cmd.exe set filetype=zsh
augroup END
nnoremap <silent><Leader>t :Deol powershell -auto-cd=v:false<CR>
'''

# view
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
    set showtabline=2
    set laststatus=2
    set noshowmode
    
    let g:lightline = {}
    let g:lightline.enable = { 'tabline': 1 }
    let g:lightline.active = {
    \   'left':  [ [ 'mode', 'paste', 'coc_info', 'coc_hints', 'coc_errors', 'coc_warnings', 'coc_ok'],
    \              [ 'gitbranch', 'diagonostic', 'coc_status', 'filename', 'modified'] ],
    \   'right': [ [ 'lineinfo' ],
    \              [ 'method', 'filetype'],
    \              [ 'fileformat', 'fileencoding' ] ]
    \   }
    let g:lightline.component_function ={
    \       'filename': 'LightlineFilename',
    \       'method': 'NearestMethodOrFunction',
    \       'filetype': 'LightlineFiletype', 
    \       'fileformat': 'LightlineFileformat', 
    \       'fileencoding': 'LightlineFileencoding', 
    \  }
    let g:lightline.component_expand = {
    \       'gitbranch': 'LightlineGitbranch',
    \       'coc_warnings': 'lightline#coc#warnings',
    \       'coc_errors': 'lightline#coc#errors',
    \       'coc_info': 'lightline#coc#info',
    \       'coc_hints': 'lightline#coc#hints',
    \       'coc_ok': 'lightline#coc#ok',
    \       'coc_status': 'coc#status',
    \   }
    let g:lightline.component_type = {
    \       'coc_warnings': 'warning',
    \       'coc_errors': 'error',
    \       'coc_info': 'info',
    \       'coc_hints': 'hints',
    \       'coc_ok': 'left',
    \   }
    let g:lightline.inactive = {
    \       'left':  [ [ 'filename' ] ],
    \       'right': [ [ 'lineinfo' ],
    \                  [ 'percent' ] ]
    \   }
    let g:lightline.tabline = {
    \       'left': [ [ 'tabs' ] ],
    \       'right': [ [ 'close' ] ] 
    \   }
    let g:lightline.separator    = { 'left': "\ue0b0", 'right': "\ue0b2" }
    let g:lightline.subseparator = { 'left': "\ue0b1", 'right': "\ue0b3" }
    function! LightlineFilename()
        let l:p = expand('%:t')
        if '' !=# l:p
            return l:p
        endif
        return '[No Name]'
    endfunction
    function! NearestMethodOrFunction() abort
        let l:func_name = get(b:, 'vista_nearest_method_or_function', '')
        if winwidth(0) <= 70
            return ''
        elseif l:func_name != ''
            return 'ïž” ' . l:func_name
        endif
        return ''
    endfunction

    function! LightlineGitbranch()
        if len(fugitive#head()) == 0
            return ''
        elseif winwidth(0) <= 70
            return ''
        else
            return "\ue0a0" . fugitive#head() . ' '
        endif
    endfunction

    function! LightlineFileformat()
        return winwidth(0) > 70 ? &fileformat : ''
    endfunction
    
    function! LightlineFiletype()
        return winwidth(0) > 70 ? (&filetype !=# '' ? &filetype : 'no ft') : ''
    endfunction
    
    function! LightlineFileencoding()
        return winwidth(0) > 70 ? (&fenc !=# '' ? &fenc : &enc) : ''
    endfunction
   
    augroup LightLineOnVista
        autocmd!
        autocmd VimEnter * call vista#RunForNearestMethodOrFunction()
    augroup END 
'''

[[plugins]]
repo = 'sainnhe/gruvbox-material'
hook_add = '''
let g:gruvbox_material_background = 'hard'
let g:gruvbox_material_statusline_style = 'original'

let g:gruvbox_material_enable_italic = 1
let g:gruvbox_material_enable_bold = 1
let g:gruvbox_material_better_performance = 1
let g:gruvbox_material_diagnostic_virtual_text = 'colored'
let g:gruvbox_material_diagnostic_text_highlight = 1
let g:gruvbox_material_diagnostic_line_highlight = 1
'''

[[plugins]]
repo = 'sainnhe/everforest'
hook_add = '''
let g:everforest_material_background = 'hard'
let g:everforest_material_statusline_style = 'original'

let g:everforest_enable_italic = 1
let g:everforest_enable_bold = 1
let g:everforest_better_performance = 1
let g:everforest_diagnostic_virtual_text = 'colored'
let g:everforest_diagnostic_text_highlight = 1
let g:everforest_diagnostic_line_highlight = 1
'''

[[plugins]]
repo = 'sainnhe/sonokai'
hook_add = '''

let g:sonokai_style = 'andromeda'

let g:sonokai_enable_italic = 1
let g:sonokai_better_performance = 1
let g:sonokai_diagnostic_virtual_text = 'colored'
let g:sonokai_diagnostic_line_highlight = 1
let g:sonokai_diagnostic_text_highlight = 1
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
nnoremap <silent><Leader>gd :Gvdiffsplit<CR>
nnoremap <silent><Leader>gb :Git blame<CR>
nnoremap <silent><Leader>gg :Git<CR>
nnoremap <silent><Leader>gw :Gwrite<CR>
nnoremap <silent><Leader>gc :Git commit<CR>
nnoremap <silent><Leader>gp :Git push<CR>
nnoremap <silent><Leader>gm :Git mergetool<CR>
'''

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
build = 'cd app && yarn install'
hook_add = '''
au Filetype markdown,pandoc.markdown,rmd nmap <Leader>r <Plug>MarkdownPreview
'''

[[plugins]]
repo = 'airblade/vim-rooter'
hook_add = '''
let g:rooter_patterns = ['.git', 'Makefile', '*.sln']
let g:rooter_change_directory_for_non_project_files = 'current'
let g:rooter_cd_cmd = 'tcd'
'''

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'unblevable/quick-scope'

[[plugins]]
repo = 'wfxr/minimap.vim'
hook_add = '''
nnoremap <silent><Leader>m :Vista!<CR>:MinimapToggle<CR>
'''

[[plugins]]
repo = 'liuchengxu/vista.vim'
hook_add = '''
let g:vista_default_executive = 'coc'
nnoremap <silent><Leader>v :MinimapClose<CR>:Vista!!<CR>
'''

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'tversteeg/registers.nvim'
