[[plugins]]
repo = 'vim-jp/syntax-vim-ex'
on_ft = 'vim'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'bfrg/vim-cpp-modern'
on_ft = ['c', 'cpp']
hook_add = '''
let g:cpp_attributes_highlight = 1
let g:cpp_member_highlight = 1
let g:cpp_simple_highlight = 1
'''
